In [1]:
import pandas as pd
import numpy as np

In [3]:
players = pd.read_csv("C:/Users/Dell/Downloads/Đồ án/Data/Full/players_transfermarket.csv")
basic_info =  pd.read_csv("C:/Users/Dell/Downloads/Đồ án/Data/Full/basic_info_with_link.csv")
stats =  pd.read_csv("C:/Users/Dell/Downloads/Đồ án/Data/Full/player_stats.csv")
injuries = pd.read_csv("C:/Users/Dell/Downloads/Đồ án/Data/Full/Injuries.csv")
awards = pd.read_csv("C:/Users/Dell/Downloads/Đồ án/Data/Full/awards.csv")
market_values = pd.read_csv("C:/Users/Dell/Downloads/Đồ án/Data/Full/market_value.csv")

Khai báo những file đã được thu thập trước đó và loại bỏ những cột thừa

In [4]:
basic_info = basic_info.drop(basic_info.columns[[0, 1, 3, 5]], axis=1)
basic_info.rename(columns={'link': 'player'}, inplace=True)
basic_info

,player,team,name,position,height,age
0,/david-de-gea/profil/spieler/59377,Manchester United,David de Gea,Goalkeeper,189.0,32.0
1,/jack-butland/profil/spieler/128899,Manchester United,Jack Butland,Goalkeeper,196.0,30.0
2,/tom-heaton/profil/spieler/34130,Manchester United,Tom Heaton,Goalkeeper,188.0,37.0
3,/lisandro-martinez/profil/spieler/480762,Manchester United,Lisandro Martínez,Defender Centre-Back,175.0,25.0
4,/raphael-varane/profil/spieler/164770,Manchester United,Raphaël Varane,Defender Centre-Back,191.0,30.0
...,...,...,...,...,...,...
10749,/aidan-simmons/profil/spieler/867763,Western Sydney Wanderers,Aidan Simmons,Attack-RightWinger,NaN,20.0
10750,/kusini-yengi/profil/spieler/708099,Western Sydney Wanderers,Kusini Yengi,Attack Centre-Forward,190.0,24.0
10751,/nathanael-blair/profil/spieler/1023268,Western Sydney Wanderers,Nathanael Blair,Attack Centre-Forward,NaN,19.0
10752,/zachary-sapsford/profil/spieler/703657,Western Sydney Wanderers,Zachary Sapsford,Attack Centre-Forward,NaN,20.0
10753,/alexander-badolato/profil/spieler/957230,Western Sydney Wanderers,Alexander Badolato,Attack Centre-Forward,170.0,18.0

In [5]:
stats = stats.drop(stats.columns[[0]], axis=1)
stats

,player,appearance,goals,assists,yellow cards,second yellow cards,red cards,goals conceded,clean sheets,minutes played
0,/david-de-gea/profil/spieler/59377,104,0.000000,0.000000,0.009585,0.0,0.000000,1.217252,0.335463,9390
1,/jack-butland/profil/spieler/128899,15,0.000000,0.000000,0.069018,0.0,0.000000,1.242331,0.207055,1304
2,/tom-heaton/profil/spieler/34130,4,0.000000,0.000000,0.000000,0.0,0.000000,0.616438,0.924658,292
3,/lisandro-martinez/profil/spieler/480762,82,0.028090,0.056180,0.224719,0.0,0.000000,0.000000,0.000000,6408
4,/raphael-varane/profil/spieler/164770,63,0.017889,0.017889,0.053667,0.0,0.000000,0.000000,0.000000,5031
...,...,...,...,...,...,...,...,...,...,...
10749,/aidan-simmons/profil/spieler/867763,16,0.175953,0.087977,0.263930,0.0,0.000000,0.000000,0.000000,1023
10750,/kusini-yengi/profil/spieler/708099,26,0.372671,0.186335,0.186335,0.0,0.000000,0.000000,0.000000,1449
10751,/nathanael-blair/profil/spieler/1023268,20,0.375000,0.000000,0.187500,0.0,0.000000,0.000000,0.000000,960
10752,/zachary-sapsford/profil/spieler/703657,17,0.312139,0.104046,0.000000,0.0,0.104046,0.000000,0.000000,865
10753,/alexander-badolato/profil/spieler/957230,21,0.000000,0.000000,0.086042,0.0,0.000000,0.000000,0.000000,1046

In [6]:
injuries = injuries.drop(injuries.columns[[0]], axis=1)
injuries

                                          player  days_injured  games_injured
0             /david-de-gea/profil/spieler/59377            42              5
1            /jack-butland/profil/spieler/128899           510             58
2               /tom-heaton/profil/spieler/34130           697             84
3       /lisandro-martinez/profil/spieler/480762           175             22
4          /raphael-varane/profil/spieler/164770           238             51
...                                          ...           ...            ...
10749       /aidan-simmons/profil/spieler/867763             0              0
10750        /kusini-yengi/profil/spieler/708099           102             18
10751    /nathanael-blair/profil/spieler/1023268             0              0
10752    /zachary-sapsford/profil/spieler/703657             0              0
10753  /alexander-badolato/profil/spieler/957230             0              0

[10754 rows x 3 columns]

In [7]:
market_values = market_values.drop(market_values.columns[[0]], axis=1)
market_values.rename(columns={'link': 'player'}, inplace=True)
market_values

                                          player  current_value  highest_value
0             /david-de-gea/profil/spieler/59377     15000000.0     70000000.0
1            /jack-butland/profil/spieler/128899      1500000.0     22000000.0
2               /tom-heaton/profil/spieler/34130       600000.0      6000000.0
3       /lisandro-martinez/profil/spieler/480762     50000000.0     50000000.0
4          /raphael-varane/profil/spieler/164770     40000000.0     80000000.0
...                                          ...            ...            ...
10749       /aidan-simmons/profil/spieler/867763        75000.0        75000.0
10750        /kusini-yengi/profil/spieler/708099       300000.0       300000.0
10751    /nathanael-blair/profil/spieler/1023268        50000.0        50000.0
10752    /zachary-sapsford/profil/spieler/703657        50000.0        50000.0
10753  /alexander-badolato/profil/spieler/957230        25000.0        25000.0

[10754 rows x 3 columns]

In [8]:
awards['player'] = awards['player'].str.replace('https://www.transfermarkt.co.uk', '')
awards['player'] = awards['player'].str.replace('erfolge', 'profil')
awards = awards.drop(awards.columns[[0]], axis=1)
awards

C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

                                          player  award
0             /david-de-gea/profil/spieler/59377     13
1            /jack-butland/profil/spieler/128899      1
2               /tom-heaton/profil/spieler/34130      4
3       /lisandro-martinez/profil/spieler/480762      9
4          /raphael-varane/profil/spieler/164770     21
...                                          ...    ...
10749       /aidan-simmons/profil/spieler/867763      0
10750        /kusini-yengi/profil/spieler/708099      0
10751    /nathanael-blair/profil/spieler/1023268      0
10752    /zachary-sapsford/profil/spieler/703657      0
10753  /alexander-badolato/profil/spieler/957230      0

[10754 rows x 2 columns]

Gộp các DataFrame lại thành 1

In [9]:
combined_df = pd.merge(basic_info, stats, on='player')
combined_df = pd.merge(combined_df, injuries, on='player')
combined_df = pd.merge(combined_df, awards, on='player')
combined_df = pd.merge(combined_df, market_values, on='player')
combined_df

,player,team,name,position,height,age,appearance,goals,assists,yellow cards,second yellow cards,red cards,goals conceded,clean sheets,minutes played,days_injured,games_injured,award,current_value,highest_value
0,/david-de-gea/profil/spieler/59377,Manchester United,David de Gea,Goalkeeper,189.0,32.0,104,0.000000,0.000000,0.009585,0.0,0.000000,1.217252,0.335463,9390,42,5,13,15000000.0,70000000.0
1,/jack-butland/profil/spieler/128899,Manchester United,Jack Butland,Goalkeeper,196.0,30.0,15,0.000000,0.000000,0.069018,0.0,0.000000,1.242331,0.207055,1304,510,58,1,1500000.0,22000000.0
2,/tom-heaton/profil/spieler/34130,Manchester United,Tom Heaton,Goalkeeper,188.0,37.0,4,0.000000,0.000000,0.000000,0.0,0.000000,0.616438,0.924658,292,697,84,4,600000.0,6000000.0
3,/lisandro-martinez/profil/spieler/480762,Manchester United,Lisandro Martínez,Defender Centre-Back,175.0,25.0,82,0.028090,0.056180,0.224719,0.0,0.000000,0.000000,0.000000,6408,175,22,9,50000000.0,50000000.0
4,/raphael-varane/profil/spieler/164770,Manchester United,Raphaël Varane,Defender Centre-Back,191.0,30.0,63,0.017889,0.017889,0.053667,0.0,0.000000,0.000000,0.000000,5031,238,51,21,40000000.0,80000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10749,/aidan-simmons/profil/spieler/867763,Western Sydney Wanderers,Aidan Simmons,Attack-RightWinger,NaN,20.0,16,0.175953,0.087977,0.263930,0.0,0.000000,0.000000,0.000000,1023,0,0,0,75000.0,75000.0
10750,/kusini-yengi/profil/spieler/708099,Western Sydney Wanderers,Kusini Yengi,Attack Centre-Forward,190.0,24.0,26,0.372671,0.186335,0.186335,0.0,0.000000,0.000000,0.000000,1449,102,18,0,300000.0,300000.0
10751,/nathanael-blair/profil/spieler/1023268,Western Sydney Wanderers,Nathanael Blair,Attack Centre-Forward,NaN,19.0,20,0.375000,0.000000,0.187500,0.0,0.000000,0.000000,0.000000,960,0,0,0,50000.0,50000.0
10752,/zachary-sapsford/profil/spieler/703657,Western Sydney Wanderers,Zachary Sapsford,Attack Centre-Forward,NaN,20.0,17,0.312139,0.104046,0.000000,0.0,0.104046,0.000000,0.000000,865,0,0,0,50000.0,50000.0
10753,/alexander-badolato/profil/spieler/957230,Western Sydney Wanderers,Alexander Badolato,Attack Centre-Forward,170.0,18.0,21,0.000000,0.000000,0.086042,0.0,0.000000,0.000000,0.000000,1046,0,0,0,25000.0,25000.0

In [38]:
injuries

                                          player  days_injured  games_injured
0             /david-de-gea/profil/spieler/59377            42              5
1            /jack-butland/profil/spieler/128899           510             58
2               /tom-heaton/profil/spieler/34130           697             84
3       /lisandro-martinez/profil/spieler/480762           175             22
4          /raphael-varane/profil/spieler/164770           238             51
...                                          ...           ...            ...
10749       /aidan-simmons/profil/spieler/867763             0              0
10750        /kusini-yengi/profil/spieler/708099           102             18
10751    /nathanael-blair/profil/spieler/1023268             0              0
10752    /zachary-sapsford/profil/spieler/703657             0              0
10753  /alexander-badolato/profil/spieler/957230             0              0

[10754 rows x 3 columns]

In [39]:
combined_df['player'].nunique()

10754

Xử lý các giá trị null

In [10]:
# Get the columns with null values
columns_with_null = combined_df.columns[combined_df.isnull().any()].tolist()

# Print the columns with null values
print(columns_with_null)

['height', 'age']

In [11]:
# Tiền xử lý cột position
def position(s):
    if s == 'Goalkeeper':
        return 1
    elif 'Defender' in s:
        return 2
    elif 'Midfield' in s:
        return 3
    else:
        return 4
def check_winger(s):
    if 'Left' in s or 'Right' in s:
        return 1
    else:
        return 0

combined_df['position_encoded'] = combined_df['position'].apply(position)
combined_df['winger'] = combined_df['position'].apply(check_winger)

In [12]:
# Tiền xử lý cột height, age
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = 'mean')
columns_with_missing = combined_df.columns[combined_df.isnull().any()].tolist()
combined_df[columns_with_missing] = imputer.fit_transform(combined_df[columns_with_missing])

In [13]:
combined_df

,player,team,name,position,height,age,appearance,goals,assists,yellow cards,...,goals conceded,clean sheets,minutes played,days_injured,games_injured,award,current_value,highest_value,position_encoded,winger
0,/david-de-gea/profil/spieler/59377,Manchester United,David de Gea,Goalkeeper,189.000000,32.0,104,0.000000,0.000000,0.009585,...,1.217252,0.335463,9390,42,5,13,15000000.0,70000000.0,1,0
1,/jack-butland/profil/spieler/128899,Manchester United,Jack Butland,Goalkeeper,196.000000,30.0,15,0.000000,0.000000,0.069018,...,1.242331,0.207055,1304,510,58,1,1500000.0,22000000.0,1,0
2,/tom-heaton/profil/spieler/34130,Manchester United,Tom Heaton,Goalkeeper,188.000000,37.0,4,0.000000,0.000000,0.000000,...,0.616438,0.924658,292,697,84,4,600000.0,6000000.0,1,0
3,/lisandro-martinez/profil/spieler/480762,Manchester United,Lisandro Martínez,Defender Centre-Back,175.000000,25.0,82,0.028090,0.056180,0.224719,...,0.000000,0.000000,6408,175,22,9,50000000.0,50000000.0,2,0
4,/raphael-varane/profil/spieler/164770,Manchester United,Raphaël Varane,Defender Centre-Back,191.000000,30.0,63,0.017889,0.017889,0.053667,...,0.000000,0.000000,5031,238,51,21,40000000.0,80000000.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10749,/aidan-simmons/profil/spieler/867763,Western Sydney Wanderers,Aidan Simmons,Attack-RightWinger,181.240353,20.0,16,0.175953,0.087977,0.263930,...,0.000000,0.000000,1023,0,0,0,75000.0,75000.0,4,1
10750,/kusini-yengi/profil/spieler/708099,Western Sydney Wanderers,Kusini Yengi,Attack Centre-Forward,190.000000,24.0,26,0.372671,0.186335,0.186335,...,0.000000,0.000000,1449,102,18,0,300000.0,300000.0,4,0
10751,/nathanael-blair/profil/spieler/1023268,Western Sydney Wanderers,Nathanael Blair,Attack Centre-Forward,181.240353,19.0,20,0.375000,0.000000,0.187500,...,0.000000,0.000000,960,0,0,0,50000.0,50000.0,4,0
10752,/zachary-sapsford/profil/spieler/703657,Western Sydney Wanderers,Zachary Sapsford,Attack Centre-Forward,181.240353,20.0,17,0.312139,0.104046,0.000000,...,0.000000,0.000000,865,0,0,0,50000.0,50000.0,4,0
10753,/alexander-badolato/profil/spieler/957230,Western Sydney Wanderers,Alexander Badolato,Attack Centre-Forward,170.000000,18.0,21,0.000000,0.000000,0.086042,...,0.000000,0.000000,1046,0,0,0,25000.0,25000.0,4,0

In [14]:
column_types = combined_df.dtypes

print(column_types)

player                  object
team                    object
name                    object
position                object
height                 float64
age                    float64
appearance               int64
goals                  float64
assists                float64
yellow cards           float64
second yellow cards    float64
red cards              float64
goals conceded         float64
clean sheets           float64
minutes played           int64
days_injured             int64
games_injured            int64
award                    int64
current_value          float64
highest_value          float64
position_encoded         int64
winger                   int64
dtype: object

In [15]:
# Lưu dữ liệu đã được xử lý
combined_df.to_csv("C:/Users/Dell/Downloads/Đồ án/Data/Full/final_data.csv")